# Generated by Django 3.0.3 on 2020-03-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('due_date', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueaction',
            name='first_exec_date',
            field=models.DateField(help_text='First time this action has to be executed'),
        ),
        migrations.AlterField(
            model_name='dueaction',
            name='last_exec_date',
            field=models.DateField(blank=True, help_text='Last time this action was executed'),
        ),
    ]
