# Generated by Django 3.0.3 on 2020-03-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('due_date', '0002_auto_20200317_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueaction',
            name='last_exec_date',
            field=models.DateField(blank=True, help_text='Last time this action was executed', null=True),
        ),
    ]
