# Generated by Django 3.0.3 on 2020-03-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('due_date', '0003_auto_20200317_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueaction',
            name='first_exec_date',
            field=models.DateField(blank=True, help_text='First time this action has to be executed', null=True),
        ),
    ]
