# Generated by Django 3.0.3 on 2020-03-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('due_date', '0004_auto_20200317_1127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DueAction',
            new_name='ToDo',
        ),
    ]
