# Generated by Django 3.0.3 on 2020-03-18 14:00

from django.conf import settings
from django.db import migrations, models
import due_date.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('due_date', '0005_auto_20200317_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='users_responsible',
            field=models.ManyToManyField(help_text='Who is responsible for doing this?', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='exec_frequency',
            field=models.IntegerField(default=1, help_text='How often do we need to do this?', validators=[due_date.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='todo',
            name='exec_interval',
            field=models.CharField(choices=[('d', 'day'), ('w', 'week'), ('m', 'month'), ('y', 'year')], default='w', help_text='Interval this has to be done.', max_length=1),
        ),
    ]
